<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prod.proto

namespace Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.ProdRespList</code>
 */
class ProdRespList extends \Google\Protobuf\Internal\Message
{
    /**
     *修饰符
     *
     * Generated from protobuf field <code>repeated .services.ProdResponse prodList = 1;</code>
     */
    private $prodList;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Services\ProdResponse[]|\Google\Protobuf\Internal\RepeatedField $prodList
     *          修饰符
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Prod::initOnce();
        parent::__construct($data);
    }

    /**
     *修饰符
     *
     * Generated from protobuf field <code>repeated .services.ProdResponse prodList = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProdList()
    {
        return $this->prodList;
    }

    /**
     *修饰符
     *
     * Generated from protobuf field <code>repeated .services.ProdResponse prodList = 1;</code>
     * @param \Services\ProdResponse[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProdList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Services\ProdResponse::class);
        $this->prodList = $arr;

        return $this;
    }

}

