<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prod.proto

namespace Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.ProdResponse</code>
 */
class ProdResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 prodStock = 1;</code>
     */
    protected $prodStock = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $prodStock
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Prod::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 prodStock = 1;</code>
     * @return int
     */
    public function getProdStock()
    {
        return $this->prodStock;
    }

    /**
     * Generated from protobuf field <code>int32 prodStock = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProdStock($var)
    {
        GPBUtil::checkInt32($var);
        $this->prodStock = $var;

        return $this;
    }

}

