<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prod.proto

namespace Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.QuerySize</code>
 */
class QuerySize extends \Google\Protobuf\Internal\Message
{
    /**
     *页码尺寸
     *
     * Generated from protobuf field <code>int32 size = 1;</code>
     */
    protected $size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $size
     *          页码尺寸
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Prod::initOnce();
        parent::__construct($data);
    }

    /**
     *页码尺寸
     *
     * Generated from protobuf field <code>int32 size = 1;</code>
     * @return int
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     *页码尺寸
     *
     * Generated from protobuf field <code>int32 size = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->size = $var;

        return $this;
    }

}

